# Generated by Django 5.1.1 on 2024-10-04 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProgramDilleriKategori",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("isim", models.CharField(max_length=50)),
                ("ustKategori", models.CharField(max_length=50)),
                ("aktifMi", models.BooleanField(default=True)),
                ("seoTitle", models.CharField(max_length=155)),
                ("seoDescription", models.TextField(blank=True, null=True)),
                ("slug", models.SlugField(blank=True, null=True, unique=True)),
            ],
            options={
                "verbose_name": "Programlama Dili",
                "verbose_name_plural": "Programlama Dilleri",
            },
        ),
    ]
