# Generated by Django 5.1.1 on 2024-10-04 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kodlar", "0004_kodlar"),
    ]

    operations = [
        migrations.AddField(
            model_name="kodlar",
            name="programlamaDili",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                to="kodlar.programlamadilleri",
            ),
            preserve_default=False,
        ),
    ]
