# Generated by Django 5.1.1 on 2024-10-08 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kodlar", "0006_profil"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profil",
            options={"verbose_name": "Profil", "verbose_name_plural": "Profiller"},
        ),
        migrations.AddField(
            model_name="profil",
            name="profil_fotografi",
            field=models.ImageField(
                default="default.png", upload_to="profil-resimleri"
            ),
        ),
    ]
