# Generated by Django 5.1.1 on 2024-10-08 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kodlar", "0007_alter_profil_options_profil_profil_fotografi"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profil",
            name="paylasim_sayisi",
            field=models.IntegerField(default=0),
        ),
    ]
