# Generated by Django 5.1.1 on 2024-10-08 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kodlar", "0009_profil_motto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profil",
            name="motto",
            field=models.CharField(default=" ", max_length=100),
        ),
    ]
