# Generated by Django 5.1.1 on 2024-10-08 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kodlar", "0011_alter_profil_motto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profil",
            name="motto",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
