# Generated by Django 5.1.1 on 2024-10-08 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kodlar", "0012_alter_profil_motto"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profil",
            name="motto",
        ),
    ]
