# Generated by Django 5.1.1 on 2024-10-08 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kodlar", "0013_remove_profil_motto"),
    ]

    operations = [
        migrations.AddField(
            model_name="profil",
            name="motto",
            field=models.CharField(
                default="Henüz bir motto eklenmedi.", max_length=255
            ),
        ),
    ]
