# Generated by Django 5.1.1 on 2024-10-09 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kodlar", "0014_profil_motto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kodlar",
            name="seoTitle",
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
    ]
