# Generated by Django 5.1.1 on 2024-10-09 22:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kodlar", "0015_alter_kodlar_seotitle"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="kodlar",
            name="seoDescription",
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
        migrations.CreateModel(
            name="KodInceleme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kodTitle", models.CharField(max_length=100)),
                ("kodDescription", models.TextField()),
                ("seoDescription", models.TextField(blank=True, null=True)),
                ("resim", models.ImageField(upload_to="kodresimleri")),
                ("tarih", models.TimeField(auto_now_add=True)),
                (
                    "kullanici",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "programlamaDili",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="kodlar.programlamadilleri",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kod Incele",
                "verbose_name_plural": "Kod Incelemeleri",
            },
        ),
    ]
