# Generated by Django 5.1.1 on 2024-10-09 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kodlar", "0016_alter_kodlar_seodescription_kodinceleme"),
    ]

    operations = [
        migrations.AddField(
            model_name="profil",
            name="son_paylasim_zamani",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
