# Generated by Django 5.1.1 on 2024-10-10 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kodlar", "0017_profil_son_paylasim_zamani"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kodinceleme",
            name="seoDescription",
            field=models.TextField(max_length=155),
        ),
    ]
