# Generated by Django 5.1.1 on 2024-10-10 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kodlar", "0018_alter_kodinceleme_seodescription"),
    ]

    operations = [
        migrations.AddField(
            model_name="kodinceleme",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
